---
title: "Rules for how to write hamza in the Arabic script"
author: "https://github.com/adamiturabi/hamza-rules"
mainfont: "Charis SIL"
output:
  bookdown::gitbook:
    css: mystyle.css
    split_by: "none"
    self_contained: yes
    pandoc_args: ["--lua-filter=trn.lua"]
    keep_md: yes
    config:
      toc:
        collapse: section
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: null
      search: yes
      fontsettings:
        theme: white
        family: serif
        size: 2
      sharing:
        facebook: yes
        github: no
        twitter: yes
        linkedin: yes
        weibo: no
        instapaper: no
        vk: no
        all: ['facebook', 'twitter', 'linkedin', 'weibo', 'instapaper']
      info: yes
---
# Preface{-}

The Arabic fonts in this article may not render correctly in the Chrome and Chromium browsers. In this case please use Firefox or Safari instead.

[بسم الله الرحمن الرحيم]{.ar}

[الحمد لله والصلاة والسلام على نبينا محمد. أما بعد:]{.ar}

# Introduction

The rules of how to write hamza in the Arabic script are quite complex. The matter is further complicated by the limitations of metal and digital font technology. We attempt to give a comprehensive set of rules for writing hamza and some recommendations for typographers and typesetters.

This article is based on findings from the author's research. Any errors reported as issues at https://github.com/adamiturabi/hamza-rules will be greatly appreciated.

# Scope

We treat only the orthography of Standard Arabic. The orthography of the Qurʾān ([الرسم العثماني]{.ar}) is not discussed.

# Seats of hamza

hamza is written in four different ways:

1. Seated on an [Ealif]{.trn}: [أ]{.ar} or [إ]{.ar}
2. Seated on an [wAw]{.trn}: [ؤ]{.ar}
3. Seated on an [yAE]{.trn}: [ئ]{.ar}
4. Unseated: [ء]{.ar}

Here are some of notes about writing hamza in the above four methods:

+ When unseated hamza comes between two letters that are joined, then it is written above the line that joins them, for example: [خَطِيءَة]{.ar} [xaTIEao]{.trn}. In this word, the [yAE]{.trn} [ي]{.ar} joins to the [tAE marbUTao]{.trn} [ة]{.ar}.
  
  As a special case, when unseated hamza comes between joined [lAm]{.trn2} and [Ealif]{.trn2} ([لا]{.ar}), then it is positioned between them thus: [لءا]{.ar}. (In most cases, this is replaced with [لآ]{.ar} as we will explain in the next point below.) And this is different from hamzah on the [Ealif]{.trn2} following the [lAm]{.trn2}: [لأ]{.ar}.

+ When unseated hamza is followed by an [Ealif]{.trn}: [ءا]{.ar},  the combination of hamza and [Ealif]{.trn} is usually written as [آ]{.ar} as a convention. Examples: [آمَنَ]{.ar} [EAmana]{.trn}, [ظَمْآن]{.ar} [PamEAn]{.trn}, [شَنَآن]{.ar} [canaEAn]{.trn}. However, when the [Ealif]{.trn} is a suffix or part of a suffix, or the hamza is doubled, or there is an [Ealif]{.trn} before the hamza then we will write [ءا]{.ar}, not [آ]{.ar}. Examples: [شَيْءَانِ]{.ar} [cayEAni]{.trn}, [سَءَّال]{.ar} [saEEAl]{.trn}, [قِرَاءَات]{.ar} [qirAEAt]{.trn}. 

+ When hamza is seated on [Ealif]{.trn}, if it has an [kasrao]{.trn}, it is written below the [Ealif]{.trn}: [إِ]{.ar}. Otherwise, it is written above the [Ealif]{.trn}: [أَ]{.ar}, [أُ]{.ar}, [أْ]{.ar}.

+ When hamza is seated on [yAE]{.trn} [ئ]{.ar} the dots of the [yAE]{.trn} are no longer written. Here's how it will appear in different positions:

  Isolated | End | Middle | Beginnning
  :--------|:----|:-------|:----------
  [ئ]{.ar}| [ـئ]{.ar}| [ـئـ]{.ar}| [ئـ]{.ar}

  Note that hamza is seated on [yAE]{.trn} in the middle position [ـئـ]{.ar} is different from unseated hamza between two joining letters [ـءـ]{.ar}.

So how do we know when to write hamza unseated and when seated? And how do we choose between its three different seats? There are a set of rules that we need to follow in order to correctly write hamza.

# Rules for determining the seat of hamza

## Without prefixes and suffixes

We will first learn how to determine the seat of hamzah for a word
without any prefix or suffix.

Hamzah can occur in three positions in a word:

1. At the beginning of the word
1. In the middle of the word
1. At the end of the word

We will treat each of these positions below.

###  At the beginning of the word

When hamza occurs in the beginning of a word, then:

a. If the hamza carries a long-[A]{.trn} vowel, it is written unseated followed by an [Ealif]{.trn} and written as [آ]{.ar}, for example [آمَنَ]{.ar} [EAmana]{.trn}.
b. If the hamza carries any other vowel, it is written seated on an [Ealif]{.trn}, and is marked with the appropriated vowel mark, for example [أَسْلَمَ]{.ar} [Easlama]{.trn}, [أُرِيدُ]{.ar} [EurIdu]{.trn}, [إِسْلَام]{.ar} [EislAm]{.trn}, [إِيمَان]{.ar} [EImAn]{.trn}, [أُوخِذَ]{.ar} [EUxipa]{.trn}. 

### In the middle of the word

The most general case is when hamza is in the middle of a word. 

Arabic has three short vowels, three long vowels, two diphthongs, and a [sukUn]{.trn}. Each of these has an order of precedence and a hamza seat.

Precedence | Vowel | Seated hamzah
:--|:------|:---
1. | [I]{.trn}/[ay]{.trn} | [ء]{.ar}
2. | [i]{.trn}            | [ئ]{.ar}
3. | [U]{.trn}/[aw]{.trn} | [ء]{.ar}
4. | [u]{.trn}            | [ؤ]{.ar}
5. | [A]{.trn}            | [ء]{.ar}
6. | [a]{.trn}            | [أ]{.ar}
7. | [◌ْ]{.ar}             | [ء]{.ar}

**Main rule:** Disregard any doubling mark [◌ّ]{.ar} and consider the vowel on the consonant before the hamza and the _shortened_ vowel on the hamza itself. Determine which of the two vowels wins by being higher in precedence in the above table. The winning vowel's seat will be the seat of the hamza.

**Sub-rule:** If the main rule determines that hamza is to be seated on [Ealif]{.trn}, and there is a long [A]{.trn} vowel on the hamza using an [Ealif]{.trn}, then hamza shall be unseated. And the combination of [ءَا]{.ar} will usually be written as [آ]{.ar}.

Examples:

| Word | Vowel on consonant before hamza | Shortened vowel on hamza | Winning vowel | Seated hamza |
|:-----|:-|:-|:-|:------|
| [هَيْءَة]{.ar} [hayEao]{.trn}     | [ay]{.trn} | [a]{.trn}  | [ay]{.trn} | [ء]{.ar} |
| [خَطِيءَة]{.ar} [xaTIEao]{.trn}   | [I]{.trn}  | [a]{.trn}  | [I]{.trn}  | [ء]{.ar} |
| [اسْتِيءَاس]{.ar} [EistIEAs]{.trn}| [I]{.trn}  | [a]{.trn}  | [I]{.trn}  | [ء]{.ar} (Exception: [ءَا]{.ar} is not written as [آ]{.ar} when the preceding vowel is [I]{.trn}.)|
| [تَوْءَم]{.ar} [tawEam]{.trn}     | [aw]{.trn} | [a]{.trn}  | [aw]{.trn} | [ء]{.ar} |
| [سَائِل]{.ar} [sAEil]{.trn}      | [A]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.ar} |
| [تَسَاؤُل]{.ar} [tasAEul]{.trn}   | [A]{.trn}  | [u]{.trn}  | [u]{.trn}  | [ؤ]{.ar} |
| [تَسَاءَلَ]{.ar} [tasAEala]{.trn}  | [A]{.trn}  | [a]{.trn}  | [A]{.trn}  | [ء]{.ar} |
| [قِرَاءَات]{.ar} [qirAEAt]{.trn}  | [A]{.trn}  | [a]{.trn}  | [A]{.trn}  | [ء]{.ar} |
| [نُوآنٌ]{.ar} [nUEAnun]{.trn}    | [U]{.trn}  | [a]{.trn} | [U]{.trn}   | [ء]{.ar} |
| [مَسْؤُول]{.ar} [masEUl]{.trn}    | [◌ْ]{.ar}   | [u]{.trn}  | [u]{.trn}  | [ؤ]{.ar} |
| [تَرْئِيس]{.ar} [tarEIs]{.trn}    | [◌ْ]{.ar}   | [i]{.trn}  | [i]{.trn}  | [ئ]{.ar} |
| [مِرْآة]{.ar} [mirEAo]{.trn}     | [◌ْ]{.ar}   | [a]{.trn}  | [a]{.trn}  | [ء]{.ar} (Using sub-rule.)|
| [ظَمْآن]{.ar} [PamEAn]{.trn}     | [◌ْ]{.ar}   | [a]{.trn}  | [a]{.trn}  | [ء]{.ar} (Using sub-rule.)|
| [مَسْأَلَة]{.ar} [masEalao]{.trn}  | [◌ْ]{.ar}   | [a]{.trn}  | [a]{.trn}  | [أ]{.ar} |
| [الْمَرْأَة]{.ar} [almarEao]{.trn} | [◌ْ]{.ar}   | [a]{.trn}  | [a]{.trn}  | [أ]{.ar} |
| [بِئْسَ]{.ar} [biEsa]{.trn}       | [i]{.trn}  | [◌ْ]{.ar}   | [i]{.trn}  | [ئ]{.ar} |
| [سُؤْل]{.ar} [suEl]{.trn}        | [u]{.trn}  | [◌ْ]{.ar}   | [u]{.trn}  | [ؤ]{.ar} |
| [كَأْس]{.ar} [kaEs]{.trn}        | [a]{.trn}  | [◌ْ]{.ar}   | [a]{.trn}  | [أ]{.ar} |
| [سُئِلَ]{.ar} [suEila]{.trn}      | [u]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.ar} |
| [يَئِسَ]{.ar} [yaEisa]{.trn}      | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.ar} |
| [رَئِيس]{.ar} [raEIs]{.trn}      | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.ar} |
| [سُؤَال]{.ar} [suEAl]{.trn}      | [u]{.trn}  | [a]{.trn}  | [u]{.trn}  | [ؤ]{.ar} |
| [رُؤُوس]{.ar} [ruEUs]{.trn}      | [u]{.trn}  | [u]{.trn}  | [u]{.trn}  | [ؤ]{.ar} |
| [لُؤَيّ]{.ar} [luEayy]{.trn}      | [u]{.trn}  | [a]{.trn}  | [u]{.trn}  | [ؤ]{.ar} |
| [شَنَآن]{.ar} [canaEAn]{.trn}    | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [ء]{.ar} (Using sub-rule.)|
| [سَأَلَ]{.ar} [saEala]{.trn}      | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [أ]{.ar} |
| [رَأَىٰ]{.ar} [raEA]{.trn}        | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [أ]{.ar} (Sub-rule doesn't apply because [A]{.trn} vowel at end represented by [ىٰ]{.ar}, not [Ealif]{.trn2}.)|
| [رَأَّسَ]{.ar} [raEEasa]{.trn}     | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [أ]{.ar} |
| [يُرَئِّسُ]{.ar} [yuraEEisu]{.trn}  | [a]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.ar} |
| [رُئِّسَ]{.ar} [ruEEisa]{.trn}     | [u]{.trn}  | [i]{.trn}  | [i]{.trn}  | [ئ]{.ar} |
| [تَفَؤُّل]{.ar} [tafaEEul]{.trn}   | [a]{.trn}  | [u]{.trn}  | [u]{.trn}  | [ؤ]{.ar} |
| [سَءَّال]{.ar} [saEEAl]{.trn}     | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [ء]{.ar} (Using sub-rule.)|
| [لَءَّال]{.ar} [laEEAl]{.trn}     | [a]{.trn}  | [a]{.trn}  | [a]{.trn}  | [ء]{.ar} (Using sub-rule.)|

### At the end of the word

When hamza occurs at the end of a word, disregard the vowel on hamza itself, and consider only the vowel on preceding consonant.
Plug it into the precedence table as above to determine the seat of hamza.

| Word | Vowel on consonant before hamza | Seated hamza |
|:-----|:-|:------|
| [دُعَاءُ]{.ar} [dueAEu]{.trn}     | [A]{.trn}  | [ء]{.ar} |
| [سُوءُ]{.ar} [sUEu]{.trn}        | [U]{.trn}  | [ء]{.ar} |
| [جِيءَ]{.ar} [jIEa]{.trn}        | [I]{.trn}  | [ء]{.ar} |
| [ضَوْءَ]{.ar} [DawEa]{.trn}       | [aw]{.trn} | [ء]{.ar} |
| [شَيْءَ]{.ar} [cayEa]{.trn}       | [ay]{.trn} | [ء]{.ar} |
| [بُطْءُ]{.ar} [buTEu]{.trn}       | [◌ْ]{.ar}   | [ء]{.ar} |
| [عِبْءُ]{.ar} [eibEu]{.trn}       | [◌ْ]{.ar}   | [ء]{.ar} |
| [شَطْءُ]{.ar} [caTEu]{.trn}       | [◌ْ]{.ar}   | [ء]{.ar} |
| [يُهَدِّئُ]{.ar} [yuhaddiEu]{.trn}  | [i]{.trn}  | [ئ]{.ar} |
| [سَيِّئُ]{.ar} [sayyiEu]{.trn}     | [i]{.trn}  | [ئ]{.ar} |
| [بَطُؤَ]{.ar} [baTuEa]{.trn}      | [u]{.trn}  | [ؤ]{.ar} |
| [يَهْدَأُ]{.ar} [yahdaEu]{.trn}    | [a]{.trn}  | [أ]{.ar} |
| [مُبْتَدَإِ]{.ar} [mubtadaEi]{.trn} | [a]{.trn}  | [إ]{.ar} |

The exception to this rule is when the previous letter is a doubled [wAw]{.trn} with an [Dammao]{.trn}.
In this case the hamza will again be unseated. Example [تَبَوُّءُ]{.ar} [tabawwuEu]{.trn}.

Note also that [مُبْتَدَإِ]{.ar} [mubtadaEi]{.trn} can be written with the hamza below the [Ealif]{.trn} because of the [i]{.trn}-mark on the hamza.
But it is also common to write it as [مُبْتَدَأ]{.ar} [mubtadaE]{.trn}, especially when the hamza is unvoweled.

## Prefixes and suffixes

### Prefixes

If hamza is in the beginning of a word, adding a prefix to the word will not alter the writing of the hamza. Examples:  

+ [لِ + أُسْتَاذِ = لِأُسْتَاذِ]{.ar}  
+ [الْ + آخِرَة = الْآخِرَة]{.ar}

### Suffixes

If hamza is at the end of a word, adding a suffix to the word can, in general, alter the writing of the hamza. 
Hamza is now, generally, treated as if it is in the middle of the word, and the rules for hamza in the middle of a word apply.
Examples:  

| Word | Vowel on consonant before hamza | Shortened vowel on hamza | Winning vowel | Seated hamza |
|:-----|:-|:-|:-|:------|
| [بَرِيءُونَ]{.ar} [barIEUna]{.trn}     | [I]{.trn}  | [u]{.trn} | [I]{.trn}   | [ء]{.ar} |
| [بَرِيءَانِ]{.ar} [barIEAni]{.trn}     | [I]{.trn}  | [a]{.trn} | [I]{.trn}   | [ء]{.ar} |
| [بَرِيءِينَ]{.ar} [barIEIna]{.trn}     | [I]{.trn}  | [i]{.trn} | [I]{.trn}   | [ء]{.ar} |
| [بَرِيءَيْنِ]{.ar} [barIEayni]{.trn}    | [I]{.trn}  | [a]{.trn} | [I]{.trn}   | [ء]{.ar} |
| [شَيْءُهُ]{.ar} [cayEuhu]{.trn}        | [ay]{.trn} | [u]{.trn} | [ay]{.trn}  | [ء]{.ar} |
| [شَيْءَهُ]{.ar} [cayEahu]{.trn}        | [ay]{.trn} | [a]{.trn} | [ay]{.trn}  | [ء]{.ar} |
| [شَيْءِهِ]{.ar} [cayEihi]{.trn}        | [ay]{.trn} | [i]{.trn} | [ay]{.trn}  | [ء]{.ar} |
| [شَيْءَانِ]{.ar} [cayEAni]{.trn}       | [ay]{.trn} | [a]{.trn} | [ay]{.trn}  | [ء]{.ar} |
| [شَيْءَيْنِ]{.ar} [cayEayni]{.trn}      | [ay]{.trn} | [a]{.trn} | [ay]{.trn}  | [ء]{.ar} |
| [مَجِيءُهُ]{.ar} [majIEuhu]{.trn}      | [I]{.trn}  | [u]{.trn} | [I]{.trn}   | [ء]{.ar} |
| [مَجِيءَهُ]{.ar} [majIEahu]{.trn}      | [I]{.trn}  | [a]{.trn} | [I]{.trn}   | [ء]{.ar} |
| [مَجِيءِهِ]{.ar} [majIEihi]{.trn}      | [I]{.trn}  | [i]{.trn} | [I]{.trn}   | [ء]{.ar} |
| [سُوئِهِ]{.ar} [sUEihi]{.trn}         | [U]{.trn}  | [i]{.trn} | [i]{.trn}   | [ئ]{.ar} |
| [ضَوْئِهِ]{.ar} [DawEihi]{.trn}        | [aw]{.trn} | [i]{.trn} | [i]{.trn}   | [ئ]{.ar} |
| [مُتَّكِئِينَ]{.ar} [muttakiEIna]{.trn}  | [i]{.trn}  | [i]{.trn} | [i]{.trn}   | [ئ]{.ar} |
| [يُبَرِّئُونَ]{.ar} [yubarriEUna]{.trn}  | [i]{.trn}  | [u]{.trn} | [i]{.trn}   | [ئ]{.ar} |
| [يُبَرَّؤُونَ]{.ar} [yubarraEUna]{.trn}  | [a]{.trn}  | [u]{.trn} | [u]{.trn}   | [ؤ]{.ar} |

There are some exceptions:

+ If the letter before the hamza has a [sukUn]{.trn} and is not [wAw]{.trn} or [yAE]{.trn},
then the hamza will be written unseated. Examples:

  +  [جُزْءَانِ]{.ar} [juzEAni]{.trn}  
  +  [عِبْءَانِ]{.ar} [eibEAni]{.trn}  
  +  [عِبْءَيْنِ]{.ar} [eibEayni]{.trn}  
  +  [بُطْءَهُ]{.ar} [buTEahu]{.trn}  
  +  [بُطْءُهُ]{.ar} [buTEuhu]{.trn}  
  +  [بُطْءِهِ]{.ar} [buTEihi]{.trn}

+ If the hamzah is after a long-[U]{.trn} vowel or an [aw]{.trn} semi-vowel, and the hamzah does not have an [i]{.trn}-mark, then it is written unseated. Examples:

  + [سُوءَهُ]{.ar} [sUEahu]{.trn}
  + [سُوءَانِ]{.ar} [sUEAni]{.trn}
  + [ضَوْءَهُ]{.ar} [DawEahu]{.trn}
  + [ضَوْءَانِ]{.ar} [DawEAni]{.trn}
  + [سُوءُهُ]{.ar} [sUEuhu]{.trn}
  + [يَسُوءُونَ]{.ar} [yasUEUna]{.trn}


([انِ]{.ar}, [يْنِ]{.ar}, [هُ]{.ar}, and [هِ]{.ar} are suffixes.)
Note that the combination [ءا]{.ar} is not written as [آ]{.ar} when the [Ealif]{.trn2} is part of the suffix.

## [tanwIn]{.trn} on final hamza

[tanwIn]{.trn} on a final hamza does not affect the writing of the hamza except in the case of [tanwIn al-fatH]{.trn}. When writing [tanwIn al-fatH]{.trn} on a hamza at the end of a word:

1. If there is an [Ealif]{.trn} before a unseated hamza [اء]{.ar}, then we don't add a silent [Ealif]{.trn} when writing [tanwIn al-fatH]{.trn}. For example [دَاء]{.ar} becomes [دَاءً]{.ar} [dAEan]{.trn}, not [دَاءًا]{.ar}.

2. Otherwise, we add the silent [Ealif]{.trn} after the hamza so that the hamza is now in the middle of the word with a suffix [Ealif]{.trn} after it. We now pretend that the hamza has an [fatHao]{.trn} and that the [Ealif]{.trn} after it is a long-[A]{.trn} vowel. Then we go through the rules for writing hamza in the middle of a word (given above) to determine how hamza will be written. We then write the [an]{.trn}-mark on the hamza. Examples:

+ [مُبْتَدَأ]{.ar} becomes [مُبْتَدَأٌ، مُبْتَدَءًا، مُبْتَدَإٍ]{.ar} 
+ [مَلْجَأ]{.ar} becomes [مَلْجَأٌ، مَلْجَءًا، مَلْجَإٍ]{.ar}
+ [جُزْء]{.ar} becomes [جُزْءٌ، جُزْءًا، جُزْءٍ]{.ar}
+ [شَيْء]{.ar} becomes [شَيْءٌ، شَيْءًا، شَيْءٍ]{.ar}
+ [سَيِّئ]{.ar} becomes [سَيِّئٌ, سَيِّئًا, سَيِّئٍ]{.ar}
+ [تَبَوُّء]{.ar} becomes [تَبَوُّءٌ, تَبَوُّءًا, تَبَوُّءٍ]{.ar}

## Variants

There are some historical and regional variants to the above rules. The main one is when the letter before hamza has a [sukUn]{.trn}, the hamza is generally written unseated. So with this variant, we write:

+ [مَسْءُول]{.ar} instead of [مَسْؤُول]{.ar}
+ [أَسْءِلَة]{.ar} instead of [أَسْئِلَة]{.ar}
+ [مَسْءَلَة]{.ar} instead of [مَسْأَلَة]{.ar}

However, this rule appears to be not consistently followed. For example, [nacEah]{.trn} is generally always written [نَشْأَة]{.ar} never [نَشْءَة]{.ar}.

A second variant is to avoid the repetition of vowel letters like [و]{.ar} and [ي]{.ar}. So they write:

1. [رُءُوس]{.ar} instead of [رُؤُوس]{.ar}.
2. [رَءِيس]{.ar} instead of [رَئِيس]{.ar}.

# Typographical limitations

Due to what appears to have been a limitation of typesetting technology in the days of typewriters, metal typography, and early digital typography, unseated hamza between two joining letters [ـءـ]{.ar} was usually written as seated on [yAE]{.trn} instead: [ـئـ]{.ar}. Because of this limitation we are now accustomed to seeing:

+ [شَيْئًا]{.ar} instead of [شَيْءًا]{.ar}
+ [خَطِيئَة]{.ar} instead of [خَطِيءَة]{.ar}
+ [هَيْئَة]{.ar} instead of [هَيْءَة]{.ar}
+ [عِبْئَيْنِ]{.ar} instead of [عِبْءَيْنِ]{.ar}

and similar variants.

These variants have pervaded to such a degree that many modern explanations on the rules of hamza orthography present the above as the correct way of writing, and modify their rules with exceptions to allow this writing.

Fortunately, advancements in digital font technology now allow us to revert back to the original rules. However, unfortunately, only very few computer fonts today actually implement this feature.

Two fonts, of which we are aware, that do allow the preferred orthography are:

1. Dr Khaled Hosny's "Amiri": https://www.amirifont.org/
2. DecoType "Naskh": https://www.decotype.com/oneliner/

With these "hamza-safe fonts" you can always use U+0621 "Arabic Letter Hamza" to type unseated hamza no matter whether it is between joining or non-joining letters. With most other fonts U+0621 "Arabic Letter Hamza" will prevent the surrounding two letters from joining.

This issue has been discussed in detail by Thomas Milo in Unicode L2/14-109: https://unicode.org/L2/L2014/14109-inline-chars.pdf.

However, the problem remains that this is a font-specific hack. It seems that the Unicode has no official guidance in this regard.

Another solution, that works with most other fonts, is to fake the correct orthography using a combination of U+0640 "Arabic Tatweel" and U+0654 "Arabic hamza above" thus [ـٔ]{.ar} to achieve the appearance of unseated hamza between two joining letters. However, this will not work when hamza is between [lAm]{.trn} and [Ealif]{.trn} in the mandatory [lam]{.trn}-[Ealif]{.trn} ligature [لا]{.ar} (correct: [لءا]{.ar}, incorrect: [لـٔا]{.ar}). Such words are rare in Standard Arabic but do exist, e.g. [لَءَّال]{.ar} [laEEAl]{.trn} meaning "pearl-seller", and [مِلْءًا]{.ar}. Perhaps the official solution ought to be that fonts absorb the tatweel and not let it affect the [lAm]{.trn}-[Ealif]{.trn} ligature when it it is input between [lAm]{.trn} and [Ealif]{.trn}.

Beware that using tatweel in this manner may also affect the searching of characters in a digital document.
